##########################################sys_clk && rst_n ##########################################
set_property PACKAGE_PIN P17 [get_ports sys_clk]
set_property PACKAGE_PIN R10 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
##########################################KEY ##########################################
set_property IOSTANDARD LVCMOS33 [get_ports key_0]
set_property PACKAGE_PIN C12 [get_ports key_0]
set_property IOSTANDARD LVCMOS33 [get_ports key_1]
set_property PACKAGE_PIN B12 [get_ports key_1]
set_property IOSTANDARD LVCMOS33 [get_ports key_2]
set_property PACKAGE_PIN B13 [get_ports key_2]
set_property IOSTANDARD LVCMOS33 [get_ports key_3]
set_property PACKAGE_PIN B14 [get_ports key_3]
set_property IOSTANDARD LVCMOS33 [get_ports key_4]
set_property PACKAGE_PIN A13 [get_ports key_4]
##########################################7_SEG##########################################
set_property IOSTANDARD LVCMOS33 [get_ports AN[0]]
set_property PACKAGE_PIN D14 [get_ports AN[0]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[1]]
set_property PACKAGE_PIN C14 [get_ports AN[1]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[2]]
set_property PACKAGE_PIN A10 [get_ports AN[2]]
set_property IOSTANDARD LVCMOS33 [get_ports AN[3]]
set_property PACKAGE_PIN A9  [get_ports AN[3]]
set_property IOSTANDARD LVCMOS33 [get_ports C[0]]
set_property PACKAGE_PIN B11 [get_ports C[0]]
set_property IOSTANDARD LVCMOS33 [get_ports C[1]]
set_property PACKAGE_PIN A11 [get_ports C[1]]
set_property IOSTANDARD LVCMOS33 [get_ports C[2]]
set_property PACKAGE_PIN F13 [get_ports C[2]]
set_property IOSTANDARD LVCMOS33 [get_ports C[3]]
set_property PACKAGE_PIN F14 [get_ports C[3]]
set_property IOSTANDARD LVCMOS33 [get_ports C[4]]
set_property PACKAGE_PIN D12 [get_ports C[4]]
set_property IOSTANDARD LVCMOS33 [get_ports C[5]]
set_property PACKAGE_PIN D13 [get_ports C[5]]
set_property IOSTANDARD LVCMOS33 [get_ports C[6]]
set_property PACKAGE_PIN D15 [get_ports C[6]]
set_property IOSTANDARD LVCMOS33 [get_ports C[7]]
set_property PACKAGE_PIN C15 [get_ports C[7]]

##########################################LED ##########################################
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property PACKAGE_PIN D10 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property PACKAGE_PIN D9 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN C9 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property PACKAGE_PIN B9 [get_ports led3]
##########################################ADC ##########################################
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
set_property PACKAGE_PIN R8 [get_ports adc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[0]]
set_property PACKAGE_PIN T8 [get_ports adc_data[0]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[1]]
set_property PACKAGE_PIN U7 [get_ports adc_data[1]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[2]]
set_property PACKAGE_PIN R7 [get_ports adc_data[2]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[3]]
set_property PACKAGE_PIN T6 [get_ports adc_data[3]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[4]]
set_property PACKAGE_PIN T5 [get_ports adc_data[4]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[5]]
set_property PACKAGE_PIN T4 [get_ports adc_data[5]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[6]]
set_property PACKAGE_PIN V2 [get_ports adc_data[6]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[7]]
set_property PACKAGE_PIN U2 [get_ports adc_data[7]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[8]]
set_property PACKAGE_PIN V4 [get_ports adc_data[8]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[9]]
set_property PACKAGE_PIN V5 [get_ports adc_data[9]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[10]]
set_property PACKAGE_PIN V6 [get_ports adc_data[10]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data[11]]
set_property PACKAGE_PIN U8 [get_ports adc_data[11]]

##########################################VGA ########################################## 
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r[4]]
set_property PACKAGE_PIN M18 [get_ports rgb_r[4]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r[3]]
set_property PACKAGE_PIN J15 [get_ports rgb_r[3]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r[2]]
set_property PACKAGE_PIN L18 [get_ports rgb_r[2]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r[1]]
set_property PACKAGE_PIN K15 [get_ports rgb_r[1]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_r[0]]
set_property PACKAGE_PIN L16 [get_ports rgb_r[0]]

set_property IOSTANDARD LVCMOS33 [get_ports rgb_g[5]]
set_property PACKAGE_PIN K16 [get_ports rgb_g[5]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g[4]]
set_property PACKAGE_PIN H16 [get_ports rgb_g[4]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g[3]]
set_property PACKAGE_PIN G16 [get_ports rgb_g[3]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g[2]]
set_property PACKAGE_PIN L15 [get_ports rgb_g[2]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g[1]]
set_property PACKAGE_PIN M17 [get_ports rgb_g[1]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_g[0]]
set_property PACKAGE_PIN P18 [get_ports rgb_g[0]]

set_property IOSTANDARD LVCMOS33 [get_ports rgb_b[4]]
set_property PACKAGE_PIN M16 [get_ports rgb_b[4]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b[3]]
set_property PACKAGE_PIN N17 [get_ports rgb_b[3]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b[2]]
set_property PACKAGE_PIN M14 [get_ports rgb_b[2]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b[1]]
set_property PACKAGE_PIN P14 [get_ports rgb_b[1]]
set_property IOSTANDARD LVCMOS33 [get_ports rgb_b[0]]
set_property PACKAGE_PIN L14 [get_ports rgb_b[0]]

set_property IOSTANDARD LVCMOS33 [get_ports hs]
set_property PACKAGE_PIN N14 [get_ports hs]
set_property IOSTANDARD LVCMOS33 [get_ports vs]
set_property PACKAGE_PIN N16 [get_ports vs]

##########################################over ##########################################
